services:
  - type: web
    name: securewatch-ai-backend
    runtime: docker
    rootDir: backend
    plan: free
    envVars:
      - key: DB_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        sync: false
      - key: JPA_DDL_AUTO
        value: update
      - key: AI_API_KEY
        sync: false
      - key: VIRUSTOTAL_API_KEY
        sync: false

  - type: web
    name: securewatch-ai-frontend
    runtime: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        sync: false
      - key: VITE_WS_URL
        sync: false
